version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_REPLICA_FETCH_MAX_BYTES: 15728640
      KAFKA_MESSAGE_MAX_BYTES: 15728640
      KAFKA_MAX_MESSAGE_BYTES: 15728640
  
  tests:
    build: .
    depends_on:
      - kafka
    volumes:
      - .:/src
    command: sh -c "sleep 20 &&  pytest"

  kafka_producer:
    build: .
    depends_on:
      - kafka
      - tests
    environment:
      KAFKA_BROKER: kafka:9092
    volumes:
      - .:/src
    command: sh -c "sleep 20 && python src/data_generator.py -bs kafka:9092 -n 10"

  kafka_consumer:
    build: .
    depends_on:
      - kafka_producer
    environment:
      KAFKA_BROKER: kafka:9092
    volumes:
      - ./output:/src/output
    command: sh -c "sleep 20 && python src/kafka_consumer.py -bs kafka:9092"